model:
  # checkpoint_path: /home/deepcybo/.cache/openpi/openpi-assets/checkpoints/pi05_droid
  checkpoint_path: /home/deepcybo/.cache/openpi/openpi-assets/checkpoints/pi05_droid_finetune_franka/chess_merged_1/29999
  chunk_steps: 10
  infer_times: 500
robot:
  action_rate_hz: 15
  damping: 0.0067
  ip: 192.168.1.104
  port: 4242
  speed: 0.01
task:
  prompt: put the red block into the 1th cell
